#%RAML 1.0 DataType

type: object
properties:
  msg:
    description: This element will display the status of failed message.
    type: string
    required: true
    example: "failed operation"
  code:
    description: This element will display status code
    type: integer
    required: true
    example: 400
  success:
    type: boolean
    required: true
    example: false
  error:
    type: object
    required: true
    properties:
      "type":
        type: string
        required: true
        example: "BAD_REQUEST"
      title: 
        type: string
        required: true            
        example: "Invalid Request"
      details:
        type: string
        required: true
        example: "The input contains invalid data"  