#%RAML 1.0 Trait

queryParameters:
  email:
    required: false
    type: string
  phoneCountry:
    required: false
    type: string
  phoneNumber:
    required: false
    type: string
  registrationDate:
    required: false
    type: string