#%RAML 1.0 Trait

headers:
  X-Cms-ClientId:
    required: true
    type: string
    example: "98hdsfhjd-76hdsfhli-76nksfhjd-67hdsfhjd"
  X-Cms-Client-Secret:
    required: true
    type: string
    example: "769458241-agheusbd-7542dgeyd-96542shyeg"