#%RAML 1.0 Trait

queryParameters:
  email:
    type: string
    required: false
    example: "abcd@gmail.com"
  phoneCountry:
    type: string
    required: false
    example: "+91"
  phoneNumber:
    type: string
    required: false
    example: "9705507254"
  registrationDate:
    type: string
    required: false
    example: "20-11-2022"
  